#  Create a 3x3x3 array with random values 

In [2]:
import numpy as np
from datetime import date, timedelta

In [3]:
arr = np.random.rand(3,3,3)
arr

array([[[0.67557942, 0.41173569, 0.05758534],
        [0.14755729, 0.0924994 , 0.33704096],
        [0.48357773, 0.47856043, 0.06496453]],

       [[0.93070014, 0.32869267, 0.21736433],
        [0.69524667, 0.96001876, 0.68903204],
        [0.19438656, 0.41385237, 0.37073615]],

       [[0.34899675, 0.1196484 , 0.2561883 ],
        [0.01037268, 0.63571994, 0.27307307],
        [0.32546424, 0.14108191, 0.76978881]]])

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:

arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#  Normalize a 5x5 random matrix

In [6]:
d = np.random.random((5,5))
dmax,dmin=d.max(),d.min()
d= (d-dmin)/(dmax-dmin)
d

array([[0.20487487, 0.        , 0.00370493, 0.70225048, 1.        ],
       [0.51178696, 0.11813813, 0.46940809, 0.39801532, 0.45190566],
       [0.08894233, 0.7202663 , 0.1760057 , 0.39510412, 0.39778271],
       [0.75363381, 0.13560677, 0.46226316, 0.32036682, 0.24546413],
       [0.00248277, 0.53998089, 0.35495522, 0.29071438, 0.75962175]])

#   How to find common values between two arrays?

In [7]:
a = np.array([2,9,12,15,20])
b = np.array([4,8,12,16,20])
c = np.intersect1d(a,b)
c

array([12, 20])

# 6.How to get the dates of yesterday, today and tomorrow?

In [11]:
today = np.datetime64('today')
ystrdy = today - np.timedelta64(1)
tmrw = today + np.timedelta64(1)
print('Todays Date: ',today)
print('Yesterday Date: ',ystrdy)
print('Tomorrow Date: ',tmrw)

Todays Date:  2020-07-28
Yesterday Date:  2020-07-27
Tomorrow Date:  2020-07-29


#  Consider two random array A and B, check if they are equal

In [13]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.41993829 0.40723754 0.811062  ]
 [0.72848356 0.07829079 0.92755105]
 [0.020439   0.14645309 0.53976527]]


Array2:
[[0.6324453  0.41983987 0.8724069 ]
 [0.40199392 0.03061802 0.83277735]
 [0.53224574 0.38052745 0.98447113]]


Equality: False


# Create random vector of size 10 and replace the maximum value by 0 

In [14]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.        , 0.06760345, 0.72453478, 0.48623307, 0.67778778,
       0.067312  , 0.26386366, 0.2025568 , 0.23460197, 0.40190922])

#  How to print all the values of an array?

In [15]:
arr = np.ones((5, 5))
print(arr)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Subtract the mean of each row of a matrix

In [16]:
arr = np.array([[1, 120, 0, 0], [2, 140, 0, 0], [3, 110, 0, 0]])
print('Initial Array:\n', arr)
print('Mean of Each row: ',arr.mean(axis=1))
mean = arr - arr.mean(axis=1, keepdims=True) 
print('\nResultant Matrix After Subtracting Mean:\n',mean)



Initial Array:
 [[  1 120   0   0]
 [  2 140   0   0]
 [  3 110   0   0]]
Mean of Each row:  [30.25 35.5  28.25]

Resultant Matrix After Subtracting Mean:
 [[-29.25  89.75 -30.25 -30.25]
 [-33.5  104.5  -35.5  -35.5 ]
 [-25.25  81.75 -28.25 -28.25]]


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [17]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([2., 6., 2., 3., 2.])

# How to get the diagonal of a dot product?

In [18]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

print("Array A:\n", A)
print("Array B:\n", B)

print('\nDot product:\n',np.dot(A,B))
dot = np.diag(np.dot(A, B))
print('\nThe Diagonal Elements are:\n', dot)

Array A:
 [[5 8 5]
 [9 1 0]
 [1 2 8]]
Array B:
 [[9 8 3]
 [0 2 2]
 [2 2 3]]

Dot product:
 [[55 66 46]
 [81 74 29]
 [25 28 31]]

The Diagonal Elements are:
 [55 74 31]


# How to find the most frequent value in an array?

In [19]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[3 3 8 0 5 8 9 5 4 8 5 9 5 5 8 1 1 2 8 2]


5

# How to get the n largest values of an array

In [20]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()



3

# How to create a record array from a regular array?

In [21]:
arra1 = np.array([("sumit", 88.5, 90),
                 ("Ayaan", 87, 99),
                 ("Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)


Original arrays:
[['sumit' '88.5' '90']
 ['Ayaan' '87' '99']
 ['Preece' '85.5' '91']]

Record array;
[(b'sumit', 88.5, 90) (b'Ayaan', 87. , 99) (b'Preece', 85.5, 91)]
